"""Add unique constraint to favorites table

Revision ID: 6be23604461b
Revises: 9f24c2a41a88
Create Date: 2025-04-09 20:49:26.895182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be23604461b'
down_revision = '9f24c2a41a88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('s')
    op.drop_table('_photos')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_photo_favorite', ['user_id', 'photo_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_photo_favorite', type_='unique')

    op.create_table('_photos',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('photo_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['_id'], ['s.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('_id', 'photo_id')
    )
    op.create_table('s',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
