"""Add updated_at to favorites

Revision ID: 9f24c2a41a88
Revises: 9f24c2a41a87
Create Date: 2025-04-03 23:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
import os

environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '9f24c2a41a88'
down_revision = '9f24c2a41a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    if environment == "production":
        op.execute(f"ALTER TABLE {SCHEMA}.favorites ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if environment == "production":
        op.execute(f"ALTER TABLE {SCHEMA}.favorites DROP COLUMN IF EXISTS updated_at")
    else:
        op.drop_column('favorites', 'updated_at')
    # ### end Alembic commands ###
